<form class="muzikanten-searchform" action="<?php get_permalink() ?>/zoekresultaten-bands/" method="post">
    <div class="muzikanten-searchform-filteroptie">
        <label for="filter-genre-band">Genre band</label><br>
        <select name="filter-genre-band">
            <option value="Alle">Alle</option>
            <option value="Diverse">Diverse</option>
            <option value="Elektronische muziek">Elektronische muziek</option>
            <option value="Folk, volksmuziek en wereldmuziek">Folk, volksmuziek en wereldmuziek</option>
            <option value="Jazz">Jazz</option>
            <option value="Klassiek">Klassiek</option>
            <option value="Latin">Latin</option>
            <option value="Pop">Pop</option>
            <option value="Rock">Rock</option>
            <option value="R&B">R&B</option>
            <option value="Schlager en levenslied">Schlager en levenslied</option>
        </select>
    </div>
    <div class="muzikanten-searchform-filteroptie">
        <label for="filter-type-band">Type Band</label><br>
        <select name="filter-type-band">
            <option value="Alle">Alle</option>
            <option value="Coverband">Coverband</option>
            <option value="Eigen materiaal">Eigen materiaal</option>
            <option value="Tribute band">Tribute band</option>
        </select>
    </div>
      <div class="muzikanten-searchform-filteroptie">
        <label for="filter-instrument-band">Gezocht instrument</label><br>
        <select name="filter-instrument-band">
            <option value="Alle">Alle</option>
            <option value="3rd Bridge Gitaar">3rd Bridge Gitaar</option>
            <option value="Aartsluit">Aartsluit</option>
            <option value="Accordeon">Accordeon</option>
            <option value="Agung">Agung</option>
            <option value="Akkoordciter">Akkoordciter</option>
            <option value="Akoestische gitaar">Akoestische gitaar</option>
            <option value="Alpenhoorn">Alpenhoorn</option>
            <option value="Altblokfluit">Altblokfluit</option>
            <option value="Althobo">Althobo</option>
            <option value="Althoorn">Althoorn</option>
            <option value="Altklarinet">Altklarinet</option>
            <option value="Altsaxofoon">Altsaxofoon</option>
            <option value="Altviool">Altviool</option>
            <option value="Amakondera">Amakondera</option>
            <option value="Angkloeng">Angkloeng</option>
            <option value="Apintie">Apintie</option>
            <option value="Aulos">Aulos</option>
            <option value="Autoharp">Autoharp</option>
            <option value="Bağlama">Bağlama</option>
            <option value="Baglamas">Baglamas</option>
            <option value="Balalaika">Balalaika</option>
            <option value="Bamboefluit">Bamboefluit</option>
            <option value="Bandola">Bandola</option>
            <option value="Bandoneon">Bandoneon</option>
            <option value="Bandurria">Bandurria</option>
            <option value="Banjo">Banjo</option>
            <option value="Bansuri">Bansuri</option>
            <option value="Baritonsaxofoon">Baritonsaxofoon</option>
            <option value="Basblokfluit">Basblokfluit</option>
            <option value="Basblokfluit">Basblokfluit</option>
            <option value="Basdrum">Basdrum</option>
            <option value="Basfluit">Basfluit</option>
            <option value="Basgitaar">Basgitaar</option>
            <option value="Basklarinet">Basklarinet</option>
            <option value="Basluit">Basluit</option>
            <option value="Bassaxofoon">Bassaxofoon</option>
            <option value="Bastrompet">Bastrompet</option>
            <option value="Bazuin">Bazuin</option>
            <option value="Beatring">Beatring</option>
            <option value="Beganna">Beganna</option>
            <option value="Beiaard">Beiaard</option>
            <option value="Bekkens">Bekkens</option>
            <option value="Berimbau">Berimbau</option>
            <option value="Blaas-bas">Blaas-bas</option>
            <option value="Blokfluit">Blokfluit</option>
            <option value="Bodhrán">Bodhrán</option>
            <option value="Bombardon">Bombardon</option>
            <option value="Bongo">Bongo</option>
            <option value="Bouzouki">Bouzouki</option>
            <option value="Bronselur">Bronselur</option>
            <option value="Buffetpiano">Buffetpiano</option>
            <option value="Bugel">Bugel</option>
            <option value="Buisklokken">Buisklokken</option>
            <option value="Cabaza">Cabaza</option>
            <option value="Cajón">Cajón</option>
            <option value="Carillon">Carillon</option>
            <option value="Carnyx">Carnyx</option>
            <option value="Castagnetten">Castagnetten</option>
            <option value="Cavaquinho">Cavaquinho</option>
            <option value="Celesta">Celesta</option>
            <option value="Cello">Cello</option>
            <option value="Chapman-stick">Chapman Stick</option>
            <option value="Charango">Charango</option>
            <option value="Chitarrone">Chitarrone</option>
            <option value="Chocallo">Chocallo</option>
            <option value="Cimbaal">Cimbaal</option>
            <option value="Cimbalom">Cimbalom</option>
            <option value="Cister">Cister</option>
            <option value="Citer">Citer</option>
            <option value="Clarino">Clarino</option>
            <option value="Clarsach">Clarsach</option>
            <option value="Claves">Claves</option>
            <option value="Clavichord">Clavichord</option>
            <option value="Clavicytherium">Clavicytherium</option>
            <option value="Claviorganum">Claviorganum</option>
            <option value="Cobza">Cobza</option>
            <option value="Concertciter">Concertciter</option>
            <option value="Concertina">Concertina</option>
            <option value="Conga">Conga</option>
            <option value="Contrabas">Contrabas</option>
            <option value="Contrabas-sarrusofoon">Contrabas-sarrusofoon</option>
            <option value="Contrafagot">Contrafagot</option>
            <option value="Cornemuse">Cornemuse</option>
            <option value="Cornet">Cornet</option>
            <option value="Cornetto">Cornetto</option>
            <option value="Cuatro">Cuatro</option>
            <option value="Cubaanse-tres">Cubaanse tres</option>
            <option value="Cümbüş">Cümbüş</option>
            <option value="Cymbaal">Cymbaal</option>
            <option value="Dansmeestersviool">Dansmeestersviool</option>
            <option value="Darabuka">Darabuka</option>
            <option value="Dhol">Dhol</option>
            <option value="Diatonische-accordeon">Diatonische accordeon</option>
            <option value="Didgeridoo">Didgeridoo</option>
            <option value="Didjeribone">Didjeribone</option>
            <option value="Djembé">Djembé</option>
            <option value="Dobro">Dobro</option>
            <option value="Doedelzak">Doedelzak</option>
            <option value="Domra">Domra</option>
            <option value="Draailier">Draailier</option>
            <option value="Drumstel">Drumstel</option>
            <option value="Duduk">Duduk</option>
            <option value="Duimpiano">Duimpiano</option>
            <option value="Dulciaan">Dulciaan</option>
            <option value="Dulcimer">Dulcimer</option>
            <option value="Dungchen">Dungchen</option>
            <option value="Dutar">Dutar</option>
            <option value="Dvojnice">Dvojnice</option>
            <option value="Dwarsfluit">Dwarsfluit</option>
            <option value="Ektar">Ektar</option>
            <option value="Elektrische gitaar">Elektrische gitaar</option>
            <option value="Engelse hoorn">Engelse hoorn</option>
            <option value="Eunuch-fluit">Eunuch-fluit</option>
            <option value="Eufonium">Eufonium</option>
            <option value="Fagot">Fagot</option>
            <option value="Fiddle">Fiddle</option>
            <option value="Fiscorn">Fiscorn</option>
            <option value="Flabiol">Flabiol</option>
            <option value="Flageolet">Flageolet</option>
            <option value="Flessenklokkenspel">Flessenklokkenspel</option>
            <option value="Floortrom">Floortrom</option>
            <option value="Flügelhorn">Flügelhorn</option>
            <option value="Fluit">Fluit</option>
            <option value="Fluitje">Fluitje</option>
            <option value="Foekepot">Foekepot</option>
            <option value="Fonograaf">Fonograaf</option>
            <option value="Gamelan">Gamelan</option>
            <option value="Gdulka">Gdulka</option>
            <option value="Gitaar">Gitaar</option>
            <option value="Gitarron">Gitarron</option>
            <option value="Glasharmonica">Glasharmonica</option>
            <option value="Glasharp">Glasharp</option>
            <option value="Glockenspiel">Glockenspiel</option>
            <option value="Gong">Gong</option>
            <option value="Grobbefoon">Grobbefoon</option>
            <option value="Grote trom">Grote trom</option>
            <option value="Guira">Guira</option>
            <option value="Guiro">Guiro</option>
            <option value="Guitaret">Guitaret</option>
            <option value="Guqin">Guqin</option>
            <option value="Gusle">Gusle</option>
            <option value="Guzheng">Guzheng</option>
            <option value="Hakkebord">Hakkebord</option>
            <option value="Hammered dulcimer">Hammered dulcimer</option>
            <option value="Hammondorgel">Hammondorgel</option>
            <option value="Hang">Hang</option>
            <option value="Hardangerviool">Hardangerviool</option>
            <option value="Harmonium">Harmonium</option>
            <option value="Harp">Harp</option>
            <option value="Harpgitaar">Harpgitaar</option>
            <option value="Heckelfoon">Heckelfoon</option>
            <option value="Helicon">Helicon</option>
            <option value="Hihat">Hihat</option>
            <option value="Hobo">Hobo</option>
            <option value="Hommel">Hommel</option>
            <option value="Hoorn">Hoorn</option>
            <option value="Hoornmirliton">Hoornmirliton</option>
            <option value="Ierse bouzouki">Ierse bouzouki</option>
            <option value="Ierse harp">Ierse harp</option>
            <option value="Indiaans-Amerikaanse fluit">Indiaans-Amerikaanse fluit</option>
            <option value="Jachthoorn">Jachthoorn</option>
            <option value="Jazzgitaar">Jazzgitaar</option>
            <option value="Kantele">Kantele</option>
            <option value="Kautele">Kautele</option>
            <option value="Kaval">Kaval</option>
            <option value="Kisa">Kisa</option>
            <option value="Kazoo">Kazoo</option>
            <option value="Kelstone">Kelstone</option>
            <option value="Kementsje">Kementsje</option>
            <option value="Keyboard">Keyboard</option>
            <option value="Khene">Khene</option>
            <option value="Klarinet">Klarinet</option>
            <option value="Klaroen">Klaroen</option>
            <option value="Klavecimbel">Klavecimbel</option>
            <option value="Kleine trom">Kleine trom</option>
            <option value="Klokkenspel">Klokkenspel</option>
            <option value="Klopflessenspel">Klopflessenspel</option>
            <option value="Koebel">Koebel</option>
            <option value="Kora">Kora</option>
            <option value="Kornet">Kornet</option>
            <option value="Kortholt">Kortholt</option>
            <option value="Koto">Koto</option>
            <option value="Kromhoorn">kromhoorn</option>
            <option value="Kwarttoonklarinet">Kwarttoonklarinet</option>
            <option value="Lamellofoon">Lamellofoon</option>
            <option value="Laud">Laud</option>
            <option value="Lier">Lier</option>
            <option value="Lira da braccio">Lira da braccio</option>
            <option value="Liuto attiorbato">Liuto attiorbato</option>
            <option value="Luit">Luit</option>
            <option value="Lure">Lure</option>
            <option value="Lyra">Lyra</option>
            <option value="Lyricon">Lyricon</option>
            <option value="Mandobas">Mandobas</option>
            <option value="Mandola">Mandola</option>
            <option value="Mandoline">Mandoline</option>
            <option value="Mandoloncello">Mandoloncello</option>
            <option value="Marimba">Marimba</option>
            <option value="Mellofoon">Mellofoon</option>
            <option value="Melodica">Melodica</option>
            <option value="Menat">Menat</option>
            <option value="Metallofoon">Metallofoon</option>
            <option value="Midwinterhoorn">Midwinterhoorn</option>
            <option value="Mirliton">Mirliton</option>
            <option value="Mondharmonica">Mondharmonica</option>
            <option value="Mondharp">Mondharp</option>
            <option value="Mondorgel">Mondorgel</option>
            <option value="Ney">Ney</option>
            <option value="Ngoni">Ngoni</option>
            <option value="Northumbrian smallpipes">Northumbrian smallpipes</option>
            <option value="Nyckelharpa">Nyckelharpa</option>
            <option value="Ocarina">Ocarina</option>
            <option value="Oed">Oed</option>
            <option value="Ondes-Martenot">Ondes-Martenot</option>
            <option value="Ophicleïde">Ophicleïde</option>
            <option value="Orgel">Orgel</option>
            <option value="Orkestklokken">Orkestklokken</option>
            <option value="Panfluit">Panfluit</option>
            <option value="Pauk">Pauk</option>
            <option value="Piano">Piano</option>
            <option value="Pianola">Pianola</option>
            <option value="Piccolo">Piccolo</option>
            <option value="Pijporgel">Pijporgel</option>
            <option value="Portugese gitaar">Portugese gitaar</option>
            <option value="Prepared gitaar">Prepared gitaar</option>
            <option value="Prepared piano">Prepared piano</option>
            <option value="Psalterium">Psalterium</option>
            <option value="Qanûn">Qanûn</option>
            <option value="Quena">Quena</option>
            <option value="Ranket">Ranket</option>
            <option value="Ratel">Ratel</option>
            <option value="Rebec">Rebec</option>
            <option value="Regaal">Regaal</option>
            <option value="Rommelpot">Rommelpot</option>
            <option value="Ruispijp">Ruispijp</option>
            <option value="Rietinstrument">Rietinstrument</option>
            <option value="Sabar">Sabar</option>
            <option value="Sambaballen">Sambaballen</option>
            <option value="Sansa">Sansa</option>
            <option value="Santoor">Santoor</option>
            <option value="Sarangi">Sarangi</option>
            <option value="Sarod">Sarod</option>
            <option value="Sarrusofoon">Sarrusofoon</option>
            <option value="Saxofoon">Saxofoon</option>
            <option value="Saz">Saz</option>
            <option value="Schalmei">Schalmei</option>
            <option value="Schuiftrompet">Schuiftrompet</option>
            <option value="Serpent">Serpent</option>
            <option value="Shamisen">Shamisen</option>
            <option value="Sheng">Sheng</option>
            <option value="Shō">Shō</option>
            <option value="Shruti-box">Shruti box</option>
            <option value="Sinding">Sinding</option>
            <option value="Sistrum">Sistrum</option>
            <option value="Sitar">Sitar</option>
            <option value="Sjofar">Sjofar</option>
            <option value="Snaartrom">Snaartrom</option>
            <option value="Snorrebot">Snorrebot</option>
            <option value="Sopraanblokfluit">Sopraanblokfluit</option>
            <option value="Sopraansaxofoon">Sopraansaxofoon</option>
            <option value="Sopraninoblokfluit">Sopraninoblokfluit</option>
            <option value="Sopraninosaxofoon">Sopraninosaxofoon</option>
            <option value="Soprillo">Soprillo</option>
            <option value="Sousafoon">Sousafoon</option>
            <option value="Spinet">Spinet</option>
            <option value="Steeldrum">Steeldrum</option>
            <option value="Superbone">Superbone</option>
            <option value="Suka">Suka</option>
            <option value="Surbahar">Surbahar</option>
            <option value="Surnai">Surnai</option>
            <option value="Sursringar">Sursringar</option>
            <option value="Symphonetta">Symphonetta</option>
            <option value="Synthesizer">Synthesizer</option>
            <option value="Tabla">Tabla</option>
            <option value="Tailedbridgegitaar">Tailedbridgegitaar</option>
            <option value="Tama">Tama</option>
            <option value="Tamboerijn">Tamboerijn</option>
            <option value="Tambori">Tambori</option>
            <option value="Tambura">Tambura</option>
            <option value="Tamburica">Tamburica</option>
            <option value="Tamtam">Tamtam</option>
            <option value="Tanbur">Tanbur</option>
            <option value="Tanpura">Tanpura</option>
            <option value="Tapan">Tapan</option>
            <option value="Taragot">Taragot</option>
            <option value="Templeblocks">Templeblocks</option>
            <option value="Tenora">Tenora</option>
            <option value="Tenorblokfluit">Tenorblokfluit</option>
            <option value="Tenorhoorn">Tenorhoorn</option>
            <option value="Tenorsaxofoon">Tenorsaxofoon</option>
            <option value="Tenortuba">Tenortuba</option>
            <option value="Teorbe">Teorbe</option>
            <option value="Theremin">Theremin</option>
            <option value="Tible">Tible</option>
            <option value="Tinwhistle">Tinwhistle</option>
            <option value="Tiple">Tiple</option>
            <option value="Tom">Tom</option>
            <option value="Trekzak">Trekzak</option>
            <option value="Triangel">Triangel</option>
            <option value="Trombone">Trombone</option>
            <option value="Trommel">Trommel</option>
            <option value="Trompet">Trompet</option>
            <option value="Tuba">Tuba</option>
            <option value="Torupill">Torupill</option>
            <option value="Turkse-trom">Turkse trom</option>
            <option value="Uilleann-pipes">Uilleann pipes</option>
            <option value="Ukelele">Ukelele</option>
            <option value="Vedel">Vedel</option>
            <option value="Vibrafoon">Vibrafoon</option>
            <option value="Vihuela">Vihuela</option>
            <option value="Vina">Vina</option>
            <option value="Viocta">Viocta</option>
            <option value="Viola-d'amore">Viola d'amore</option>
            <option value="Viola-da-gamba">Viola da gamba</option>
            <option value="Violoncello-(cello)">Violoncello (Cello)</option>
            <option value="Violoncello-piccolo">Violoncello piccolo</option>
            <option value="Viool">Viool</option>
            <option value="Virginaal">Virginaal</option>
            <option value="Vleugel">Vleugel</option>
            <option value="Wagnertuba">Wagnertuba</option>
            <option value="Wasbord">Wasbord</option>
            <option value="Westerngitaar">Westerngitaar</option>
            <option value="Windgong">Windgong</option>
            <option value="Windklok">Windklok</option>
            <option value="Woodblock">Woodblock</option>
            <option value="Xaphoon">Xaphoon</option>
            <option value="Xylofoon">Xylofoon</option>
            <option value="Yatga">Yatga</option>
            <option value="Yoochin">Yoochin</option>
            <option value="Zang mannenstem">Zang mannenstem</option>
            <option value="Zang vrouwenstem">Zang vrouwenstem</option>
            <option value="Zheng">Zheng</option>
            <option value="Zingende zaag">Zingende zaag</option>
            <option value="Zingende kaars">Zingende kaars</option>
            <option value="Zink">Zink</option>
            <option value="Zither">Zither</option>
            <option value="Zobo">Zobo</option>
            <option value="Zummara">Zummara</option>
            <option value="Zurla">Zurla</option>
            <option value="Zurna (Zurla)">Zurna (Zurla)</option>
        </select>
    </div>

    <label for="search">Zoek op naam</label><br>
    <input type="text" name="s" id="search" value="<?php the_search_query(); ?>" />
    <input class="zoekglas" type="image" alt="Zoek" src="/wp-content/themes/bandfit/img/bandfit-zoekglas.png" />
</form>
